// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Job struct {
	ID                  int64          `json:"id"`
	Slug                sql.NullString `json:"slug"`
	VehicleID           sql.NullInt64  `json:"vehicle_id"`
	PackageID           sql.NullInt64  `json:"package_id"`
	Technician          sql.NullString `json:"technician"`
	Notes               sql.NullString `json:"notes"`
	CompletedAt         sql.NullTime   `json:"completed_at"`
	DurationActual      sql.NullInt64  `json:"duration_actual"`
	Featured            sql.NullBool   `json:"featured"`
	DisplayPrice        sql.NullInt64  `json:"display_price"`
	HighlightText       sql.NullString `json:"highlight_text"`
	CustomerTestimonial sql.NullString `json:"customer_testimonial"`
	CustomerName        sql.NullString `json:"customer_name"`
	MetaDescription     sql.NullString `json:"meta_description"`
	MetaKeywords        sql.NullString `json:"meta_keywords"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}

type Medium struct {
	ID        int64          `json:"id"`
	JobID     sql.NullInt64  `json:"job_id"`
	VehicleID sql.NullInt64  `json:"vehicle_id"`
	Url       string         `json:"url"`
	Kind      sql.NullString `json:"kind"`
	SortOrder sql.NullInt64  `json:"sort_order"`
	AltText   sql.NullString `json:"alt_text"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Package struct {
	ID          int64          `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	ShortDesc   sql.NullString `json:"short_desc"`
	LongDesc    sql.NullString `json:"long_desc"`
	PriceMin    sql.NullInt64  `json:"price_min"`
	PriceMax    sql.NullInt64  `json:"price_max"`
	DurationEst sql.NullInt64  `json:"duration_est"`
	IsActive    sql.NullBool   `json:"is_active"`
	SortOrder   sql.NullInt64  `json:"sort_order"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Post struct {
	ID          int64          `json:"id"`
	Slug        string         `json:"slug"`
	Title       string         `json:"title"`
	Excerpt     sql.NullString `json:"excerpt"`
	Body        sql.NullString `json:"body"`
	Author      sql.NullString `json:"author"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Review struct {
	ID         int64          `json:"id"`
	Author     string         `json:"author"`
	Rating     sql.NullInt64  `json:"rating"`
	Body       sql.NullString `json:"body"`
	Source     sql.NullString `json:"source"`
	IsFeatured sql.NullBool   `json:"is_featured"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Vehicle struct {
	ID                   int64          `json:"id"`
	Slug                 string         `json:"slug"`
	Vin                  sql.NullString `json:"vin"`
	Year                 sql.NullInt64  `json:"year"`
	Make                 string         `json:"make"`
	Model                string         `json:"model"`
	Trim                 sql.NullString `json:"trim"`
	Color                sql.NullString `json:"color"`
	Price                sql.NullInt64  `json:"price"`
	StockNumber          sql.NullString `json:"stock_number"`
	DealershipName       sql.NullString `json:"dealership_name"`
	DealershipLogoUrl    sql.NullString `json:"dealership_logo_url"`
	DealershipListingUrl sql.NullString `json:"dealership_listing_url"`
	DealershipLocation   sql.NullString `json:"dealership_location"`
	Status               sql.NullString `json:"status"`
	PostedAt             sql.NullTime   `json:"posted_at"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}
