// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Booking struct {
	ID              int64          `json:"id"`
	CustomerName    string         `json:"customer_name"`
	Email           string         `json:"email"`
	Phone           sql.NullString `json:"phone"`
	VehicleDetails  sql.NullString `json:"vehicle_details"`
	ServiceInterest sql.NullString `json:"service_interest"`
	Notes           sql.NullString `json:"notes"`
	RequestedStart  time.Time      `json:"requested_start"`
	RequestedEnd    time.Time      `json:"requested_end"`
	Status          sql.NullString `json:"status"`
	Source          sql.NullString `json:"source"`
	InternalNotes   sql.NullString `json:"internal_notes"`
	ClerkUserID     sql.NullString `json:"clerk_user_id"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type GalleryGroup struct {
	ID           int64          `json:"id"`
	Title        string         `json:"title"`
	Slug         string         `json:"slug"`
	VehicleMake  sql.NullString `json:"vehicle_make"`
	VehicleModel sql.NullString `json:"vehicle_model"`
	VehicleYear  sql.NullInt64  `json:"vehicle_year"`
	Description  sql.NullString `json:"description"`
	IsFeatured   sql.NullBool   `json:"is_featured"`
	SortOrder    sql.NullInt64  `json:"sort_order"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Medium struct {
	ID             int64          `json:"id"`
	GalleryGroupID sql.NullInt64  `json:"gallery_group_id"`
	Url            string         `json:"url"`
	Kind           sql.NullString `json:"kind"`
	SortOrder      sql.NullInt64  `json:"sort_order"`
	AltText        sql.NullString `json:"alt_text"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Package struct {
	ID          int64          `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	ShortDesc   sql.NullString `json:"short_desc"`
	LongDesc    sql.NullString `json:"long_desc"`
	PriceMin    sql.NullInt64  `json:"price_min"`
	PriceMax    sql.NullInt64  `json:"price_max"`
	DurationEst sql.NullInt64  `json:"duration_est"`
	IsActive    sql.NullBool   `json:"is_active"`
	SortOrder   sql.NullInt64  `json:"sort_order"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Review struct {
	ID         int64          `json:"id"`
	Author     string         `json:"author"`
	Rating     sql.NullInt64  `json:"rating"`
	Body       sql.NullString `json:"body"`
	Source     sql.NullString `json:"source"`
	IsFeatured sql.NullBool   `json:"is_featured"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}
