// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "detailingpass/web/templates"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templates.Hero(
				"About Detailing Pass",
				"Passionate about perfection. Dedicated to detail.",
				"",
				"",
			).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <section class=\"container mx-auto px-4 py-16\"><div class=\"max-w-3xl mx-auto prose prose-invert\"><h2 class=\"text-3xl font-heading font-bold mb-4\">Our Story</h2><p class=\"text-muted mb-6\">At Detailing Pass, we believe every vehicle deserves to look its absolute best. Founded with a passion for automotive excellence, we've built our reputation on delivering premium detailing services that exceed expectations. Our partnership with leading dealerships and individual clients reflects our commitment to quality and attention to detail.</p><p class=\"text-muted mb-6\">What sets us apart is our dedication to using only professional-grade products, our meticulous attention to every detail, and our team of certified technicians who treat every vehicle as if it were their own. We don't just clean cars—we restore them to showroom condition and protect your investment for the long term.</p><h2 class=\"text-3xl font-heading font-bold mb-4 mt-12\">Our Process</h2><div class=\"grid grid-cols-1 md:grid-cols-3 gap-8 not-prose\"><div><div class=\"text-4xl font-bold text-brand-accent mb-2\">01</div><h3 class=\"text-xl font-heading font-semibold mb-2\">Inspection</h3><p class=\"text-muted\">Thorough assessment of your vehicle's condition and needs.</p></div><div><div class=\"text-4xl font-bold text-brand-accent mb-2\">02</div><h3 class=\"text-xl font-heading font-semibold mb-2\">Detailing</h3><p class=\"text-muted\">Professional treatment using premium products and techniques.</p></div><div><div class=\"text-4xl font-bold text-brand-accent mb-2\">03</div><h3 class=\"text-xl font-heading font-semibold mb-2\">Final Check</h3><p class=\"text-muted\">Quality inspection ensuring every detail meets our standards.</p></div></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = templates.Layout("About Us").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
