// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"bg-brand-secondary border-b border-border sticky top-0 z-50\"><nav class=\"container mx-auto px-4 py-4\" aria-label=\"Main navigation\"><div class=\"flex items-center justify-between\"><a href=\"/\" class=\"flex items-center gap-2 group\"><img src=\"/static/images/logo.png\" alt=\"Detailing Pass Logo\" class=\"h-8 w-auto\"> <span class=\"text-xl font-heading font-bold text-brand-accent group-hover:text-brand-fg transition\">Detailing Pass</span></a><!-- Desktop Navigation --><div class=\"hidden md:flex items-center gap-8\"><a href=\"/services\" class=\"nav-link\">Services</a> <a href=\"/work\" class=\"nav-link\">Our Work</a> <a href=\"/reviews\" class=\"nav-link\">Reviews</a> <a href=\"/about\" class=\"nav-link\">About</a> <a href=\"/blog\" class=\"nav-link\">Blog</a> <a href=\"/contact\" class=\"btn-primary\">Book Now</a></div><!-- Mobile Menu Button --><button id=\"mobile-menu-btn\" class=\"md:hidden text-brand-fg focus:outline-none focus:ring-2 focus:ring-brand-accent rounded\" aria-label=\"Toggle menu\" aria-expanded=\"false\"><svg class=\"w-6 h-6\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\"></path></svg></button></div><!-- Mobile Navigation --><div id=\"mobile-menu\" class=\"hidden md:hidden mt-4 pb-4 border-t border-border pt-4\"><div class=\"flex flex-col gap-4\"><a href=\"/services\" class=\"nav-link\">Services</a> <a href=\"/work\" class=\"nav-link\">Our Work</a> <a href=\"/reviews\" class=\"nav-link\">Reviews</a> <a href=\"/about\" class=\"nav-link\">About</a> <a href=\"/blog\" class=\"nav-link\">Blog</a> <a href=\"/contact\" class=\"btn-primary inline-block text-center\">Book Now</a></div></div></nav></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
